# NumPy 和陣列導向的程式設計

`NumPy` 可以說是 Python 中最最標準的科學計算、數據分析套件。也因為 `NumPy` 的出現, 讓 Python 有了非常好的數據分析基礎, 一直到現在成為數據分析覇主。

In [1]:
import numpy as np

## 1. 陣列導向 101

科學計算一個很核心的概念叫 "array oriented" 的寫法。Array 是 `numpy` 標準的資料結構, 和 list 很像, 但就差了那麼一點點。而這一點點讓我們在計算上是無比的方便。

### 【暖身】 計算平均

某位同學期中考各科成績如下, 請幫他計算成績。

    grades = [77, 85, 56, 90, 66]
    
請計算平均。

In [2]:
s = 0
grades = [77,85,56,90,66]
for i in grades:
    s = s+i
print("average = {0:3.2f},sum={1}".format(s/len(grades),s))

average = 74.80,sum=374


### 【示範】陣列導向

In [3]:
grades = [77,85,56,90,66]
arr=np.array(grades)
arr.mean()


np.float64(74.8)

最大值

In [4]:
arr.max()

np.int64(90)

標準差

In [5]:
arr.std()

np.float64(12.416118556135006)

### 【暖身】 換算匯率

假設今天我想查查號稱 Pentax 三公主的 31mm, 43mm, 77mm 三隻 limited 鏡頭在美國賣多少。於是我去 B&H 查了他們的價格分別是:

    prices = [1096.95, 596.95, 896.95]
    
我又查了 Google 匯率 1 美金為 31.71 元。請把三支鏡頭的價格換算為台幣。

In [6]:
prices = [1096.95, 596.95, 896.95]
usd2twd=31.71
twdprice=[]
for i in prices:
    twdprice.append(i*usd2twd)
print(twdprice)



[34784.2845, 18929.2845, 28442.2845]


先不管這實在有夠醜的數字, 我們要記得在科學計算中:

### 儘可能不要使用迴圈

這可能嗎?

### 【示範】陣列換算匯率

In [7]:
arr=np.array(prices)
arr=arr*31.71
print(arr)

[34784.2845 18929.2845 28442.2845]


哦哦, 傑克, 這太神奇了!

## 2. 其實 array 還有很多功能

### 【練習】 成績計算

一位老師成績這樣算的:

* 平時成績 20%
* 期中考   35%
* 期未考   45%

有位同學

* 平時成績 85 分
* 期中 70 分
* 期末 80 分

這位同學的學期成績是多少?

In [8]:
grades = np.array([85,70,80])
weights = np.array([0.2, 0.35, 0.45])

這還不是我們要的最終成績啊!

In [9]:
weights_grades=grades*weights
weights_grades.sum()

np.float64(77.5)

### 【提示】 array 還有很多函數可以用

可以先打入

    weighted_grades.
    
先不要按 `enter` 或 `shift-enter`, 而是按 `tab`...


### 【技巧】 一行完成成績計算

In [10]:
np.dot(grades,weights)

np.float64(77.5)

## 3. 重要的 array 大變身!

我們在數據分析, 常常要改 array 的型式。

### 【練習】 一個 50 個數字的 array

先想辦法、用亂數做出 50 個數字的 array, 叫做 A 好了。

In [11]:
A=np.random.rand(50)
print(A)

[0.6070956  0.39233816 0.47575677 0.03379685 0.95779173 0.7746391
 0.7736209  0.50050705 0.68240928 0.40511002 0.94211985 0.77213723
 0.72123396 0.25684737 0.5766556  0.79544583 0.09526972 0.58163311
 0.78153928 0.31072288 0.76152714 0.94808619 0.26237369 0.70451277
 0.44245533 0.06642311 0.81629119 0.25228696 0.57690714 0.73352905
 0.37000482 0.18275664 0.06722264 0.27307028 0.91858134 0.52858895
 0.59579964 0.6053854  0.37955546 0.52256642 0.07863366 0.93670566
 0.73988242 0.62826352 0.18261881 0.86705827 0.41531    0.4883086
 0.2396576  0.13782552]


In [12]:

A.shape = (5,10)
A

array([[0.6070956 , 0.39233816, 0.47575677, 0.03379685, 0.95779173,
        0.7746391 , 0.7736209 , 0.50050705, 0.68240928, 0.40511002],
       [0.94211985, 0.77213723, 0.72123396, 0.25684737, 0.5766556 ,
        0.79544583, 0.09526972, 0.58163311, 0.78153928, 0.31072288],
       [0.76152714, 0.94808619, 0.26237369, 0.70451277, 0.44245533,
        0.06642311, 0.81629119, 0.25228696, 0.57690714, 0.73352905],
       [0.37000482, 0.18275664, 0.06722264, 0.27307028, 0.91858134,
        0.52858895, 0.59579964, 0.6053854 , 0.37955546, 0.52256642],
       [0.07863366, 0.93670566, 0.73988242, 0.62826352, 0.18261881,
        0.86705827, 0.41531   , 0.4883086 , 0.2396576 , 0.13782552]])

### 【技巧】 檢查 A 的 `shape`

In [13]:
A.shape

(5, 10)

### 【技巧】 更改 A 的 shape

In [14]:

A.shape = (5,10)
A[0,0]

np.float64(0.6070956038184286)

### 【技巧】 也可以用 `reshape`

但要注意, reshape 並沒有改原來的陣列。

In [15]:
A.reshape(10,5)

array([[0.6070956 , 0.39233816, 0.47575677, 0.03379685, 0.95779173],
       [0.7746391 , 0.7736209 , 0.50050705, 0.68240928, 0.40511002],
       [0.94211985, 0.77213723, 0.72123396, 0.25684737, 0.5766556 ],
       [0.79544583, 0.09526972, 0.58163311, 0.78153928, 0.31072288],
       [0.76152714, 0.94808619, 0.26237369, 0.70451277, 0.44245533],
       [0.06642311, 0.81629119, 0.25228696, 0.57690714, 0.73352905],
       [0.37000482, 0.18275664, 0.06722264, 0.27307028, 0.91858134],
       [0.52858895, 0.59579964, 0.6053854 , 0.37955546, 0.52256642],
       [0.07863366, 0.93670566, 0.73988242, 0.62826352, 0.18261881],
       [0.86705827, 0.41531   , 0.4883086 , 0.2396576 , 0.13782552]])

### 【技巧】 拉平 `ravel`

雖然你想一想就知道可以用 `shape` 或 `reshape` 把多維陣列拉成一維。不過用 `ravel` 很潮。

In [16]:
A.ravel()

array([0.6070956 , 0.39233816, 0.47575677, 0.03379685, 0.95779173,
       0.7746391 , 0.7736209 , 0.50050705, 0.68240928, 0.40511002,
       0.94211985, 0.77213723, 0.72123396, 0.25684737, 0.5766556 ,
       0.79544583, 0.09526972, 0.58163311, 0.78153928, 0.31072288,
       0.76152714, 0.94808619, 0.26237369, 0.70451277, 0.44245533,
       0.06642311, 0.81629119, 0.25228696, 0.57690714, 0.73352905,
       0.37000482, 0.18275664, 0.06722264, 0.27307028, 0.91858134,
       0.52858895, 0.59579964, 0.6053854 , 0.37955546, 0.52256642,
       0.07863366, 0.93670566, 0.73988242, 0.62826352, 0.18261881,
       0.86705827, 0.41531   , 0.4883086 , 0.2396576 , 0.13782552])

## 4. 快速 array 生成法

### 【技巧】 都是 0 的 array

In [17]:
np.zeros(10)
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### 【技巧】 都是 1 的 array

In [18]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

### 【技巧】單位矩陣

In [19]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

### 【技巧】給定範圍均勻生出 n 個點

In [20]:
x=np.linspace(1,10,10)
x

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

### 【技巧】`range` 的 array 版

就是 `arange`。

In [21]:
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

## 5. 超重要 `axis` 觀念

初學 `numpy` 很多人有點弄不清楚 `axis` 概念。其實掌握矩陣, 或很像矩陣的陣列都是「先列後行」就可以!

我們先弄個 array 來練習。

In [22]:
x.ravel()
x2=x.reshape(2,5)
x2.sum(axis=0)

array([ 7.,  9., 11., 13., 15.])

In [23]:
x.sum()

np.float64(55.0)

### 【重點】 一列一列算下來是 `axis=0`

In [24]:
x2.sum(axis=0)

array([ 7.,  9., 11., 13., 15.])

![axis=0](images/axis0.png)

In [25]:
x2.sum(axis=0)

array([15., 40.])

### 【重點】 一行一行算過去是 `axis=1`

![axis=1](images/axis1.png)

In [26]:
x2.sum(axis=1)

array([15., 40.])

### 【提示】當然也有可能全部算

In [31]:
x2.sum()

np.float64(55.0)

## 6. array 過濾器

篩出我們要的資料, 這樣的技巧非常重要!

### 【例子】篩出大於 0 的數

我們有個陣列, 想找出大於 0 的數。<br>
L = np.array([3, -2, -1, 5, 7, -3])

In [28]:
L = np.array([3, -2, -1, 5, 7, -3])

我們可以很白痴的自己判斷...<br>
c = np.array([True,False,False,True,True,False])

In [29]:
c = np.array([True,False,False,True,True,False])

這是做啥呢? 我們可以瞬間...

In [32]:
L[c]

array([3, 5, 7])

除了自己做很白痴, 這看來很厲害!

事實上我們可以叫 `numpy` 做!

In [33]:
L>0

array([ True, False, False,  True,  True, False])

這有點強, 我們還可以一次到位!

In [36]:
L=L[L>0]
L

array([3, 5, 7])

## 7. 次元切割刀

`numpy` 中 array 的切割法和 list 很像。

In [47]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x[3:7]
x[2:5]

### 【技巧】2維陣列切法

記得先列後行!

In [49]:
x=x.reshape(2,5)
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

要所有的row, 切出行 1-3 位置。

In [50]:
x[:,1:3]

array([[1, 2],
       [6, 7]])

要所有的行col, 切出第 1 列row!

In [51]:
x[1:]

array([[5, 6, 7, 8, 9]])

## 8. `NumPy` 的 `zip` 和 `unzip`

之前我們介紹 list 可以用 `zip` 和 `unzip` (其實還是 `zip`) 做到的資料格式變換, 在 array 中怎麼做呢?

![zip and unzip](images/zip.png)

### 【重點】array 的 `zip`

![array zip](images/arrzip.png)

In [60]:
x = np.array([1,2,3,4])
y = np.array([5,6,7,8])

In [61]:
X= np.c_[x,y]
X

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [62]:
Y = np.r_[x,y]
Y

array([1, 2, 3, 4, 5, 6, 7, 8])

### 【重點】array 的 `unzip`

這裡其實只需要用到 array 的切割法...

![array zip](images/arrunzip.png)

In [64]:
X[:,1]

array([5, 6, 7, 8])